catchpoint:
  apikey: <API_KEY>
  application:
    name: notification-service
    classname: java
  report:
    rest:
      baseurl: https://collector-qa.tracing.catchpoint.net/v1/
  trace:
    instrument:
      traceableconfig1: com.sqlcinema.backend.notificationservice.services.*.*[traceLineByLine=true]
      traceableconfig2: com.sqlcinema.backend.notificationservice.model.*.*[traceLineByLine=true]
    integrations:
      spring:
        web:
          request:
            mask: false
          response:
            mask: false
